### ISSUE TITLE
Mac下的mark.json文件路径找不到

### ISSUE THREAD

**Issue by llnancy** [Redns/picgo-plugin-autobackup#5]

**Comment by Redns** [comment]
有修改过文件路径吗？图片是否能正常备份至文件夹呢？

**Comment by llnancy** [comment]
> 有修改过文件路径吗？图片是否能正常备份至文件夹呢？

没有修改过，默认的配置，就是不知道{picgo安装目录}在哪....

**Comment by Redns** [comment]
看下这篇 [文章](https://juejin.cn/post/6970608743041990664) 吧，我不太熟悉 `MacOS`，如果还是找不到就试着改成绝对路径吧😂

**Comment by llnancy** [comment]
突然发现备份功能正常了，路径是默认的`Autobackup/mark.json`
