### ISSUE TITLE
无法启动插件

### ISSUE THREAD

**Issue by livelycode36** [Redns/picgo-plugin-autobackup#6]
picgo日志：
`
2022-05-11 10:34:51 [PicGo ERROR] startup error
------Error Stack Begin------
Error: ENOENT: no such file or directory, open 'Autobackup/mark.json'
    at Object.openSync (fs.js:447:3)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as openSync] (electron/js2c/asar.js:138:31)
    at Object.writeFileSync (fs.js:1206:35)
    at ReadFileContext.callback (C:\Users\HelloKitty\AppData\Roaming\picgo\node_modules\picgo-plugin-autobackup\src\index.js:100:24)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:246:13)
-------Error Stack End-------
`

picgo配置文件：
`
  "picgoPlugins": {
    "picgo-plugin-super-prefix": true,
    "picgo-plugin-auto-delete": true,
    "picgo-plugin-autobackup": true
  },
  "debug": true,
  "PICGO_ENV": "GUI",
  "needReload": false,
  "picgo-plugin-super-prefix": {
    "fileFormat": "",
    "prefixFormat": "YYYY/MM/DD/"
  }
`
picgo版本：2.3.0
插件版本：1.4.10
在picgo安装目录下，**确实没有Autobackup/mark.json这个文件**
picgo的插件目录，也没有发现这个文件，我该如何获取这个文件呢？

**Comment by Redns** [comment]
试试手动创建，内容为：{"total":0,"images":[]}

**Comment by livelycode36** [comment]
手动创建可用！！可以复制图片到指定目录，好像不会像阿里云oss那样创建 日期子目录

**Comment by Redns** [comment]
嗯这个后续会添加，因为一开始我觉得图片备份主要是为了恢复，所以只要让恢复应用能正确读取就行，没有太考虑图片日期分类这些😂

**Comment by livelycode36** [comment]
感谢您了，不过还有个bug，我使用了插件 [super-prefix](https://github.com/gclove/picgo-plugin-super-prefix)，发现此插件复制之后图片实际路径是D:/MarkDownImages/xxx.png，但是mark.json中存储的是"path":"D:/MarkDownImages/2022/05/11/xxx.png",

**Comment by Redns** [comment]
这个实现起来比较麻烦，因为 `Picgo` 上传流程是由很多部分组成的：
![image](https://user-images.githubusercontent.com/69022576/167771405-4cfbeba3-b0ba-49aa-a37b-db76a95fbc09.png)
该插件备份图片的部分属于 `beforeUpload`，写入 `mark.json` 的部分属于 `afterUpload`，`super-prefix` 属于 `beforeUpload`。 `Picgo` 会调用所有的 `beforeUpload` 但没有指明调用的顺序，所以就可能出现两种情况：
1. 调用该插件（此时图片还没有重命名）---> 调用 `super-prefix` （图片名称更改）---> 写入 `mark.json` 的文件名与存储的不同
2. 调用 `super-prefix` ---> 调用该插件 ---> 写入 `mark.json` 的文件名与存储的相同

我猜测调用顺序可能与插件安装先后顺序有关，你可以尝试重新安装 `super-prefix`（确保 `super-prefix` 在该插件后面调用）。
<br/>

### 为什么不在 afterUpload 处备份图片？
因为部分 `uploader` 会在上传完成后清除图片数据，所以插件可能获取不到，为保证兼容性只能在 `beforeUpload` 处保存图片

**Comment by livelycode36** [comment]
多谢大佬讲解如此详细。我删除`super-prefix`并重新安装（确保 `autobackup`在`super-prefix`之前进行安装） 又或者，更改了picgo的配置文件中`插件的顺序`。
结果还是情况1

> 调用该插件（此时图片还没有重命名）---> 调用 super-prefix （图片名称更改）---> 写入 mark.json 的文件名与存储的不同

我又安装了`auto-delete 1.0.1`一起测试，如大佬所说：
> 因为部分 uploader 会在上传完成后清除图片数据，所以插件可能获取不到，

整体调用顺序
`autobackup`(实际本地保存) --> `super-prefix`(图片重命名) --> `mark.json`(保存重命名后的路径) --> `auto-delete`(删除autobackup备份的图片)

`auto-delete`在没安装`autobackup`的情况下会删除，typora的本地图片备份；安装`autobackup`之后，删除`autobackup`的备份，不删除typora的本地备份？

好吧，那我就调整一下插件的使用，感谢大佬解惑！

**Comment by Redns** [comment]
我下个版本直接把日期分类这个功能集成进来吧，看官方的计划表，目前还没有关于插件调用顺序设置方面的

**Comment by livelycode36** [comment]
感恩的心感谢有你😘

**Comment by Redns** [comment]
突然发现已经有做的很完善的重命名插件 [rename-file](https://github.com/liuwave/picgo-plugin-rename-file) 了，所以这个插件就不直接做了。现在图片写入的部分放在了 `afterUpload` 部分，可以自适应各种重命名

**Comment by livelycode36** [comment]
> 突然发现已经有做的很完善的重命名插件 [rename-file](https://github.com/liuwave/picgo-plugin-rename-file) 了，所以这个插件就不直接做了。现在图片写入的部分放在了 `afterUpload` 部分，可以自适应各种重命名

好，那我使用一下看看！感谢你
