### ISSUE TITLE
无法本地备份问题

### ISSUE THREAD

**Issue by summer-ning** [Redns/picgo-plugin-autobackup#7]
我看之前有人提过不能本地备份的问题，说切换到坚果云再切回来就可以了，我试了一下，确实可以了。
之所以能够解决是因为如果没有手动设置存储的位置，在picgo的data.json中自动生成的配置是"space": "local",local的首字母是小写了，手动改成Local或者在GUI的配置中选择Local就可以了。

**Comment by Redns** [comment]
确实是这样，感谢反馈！
