### ISSUE TITLE
本地备份支持webdav吗？

### ISSUE THREAD

**Issue by Hello-XPH** [Redns/picgo-plugin-autobackup#9]
坚果云应该也是使用发webdav备份的，本地局域网webdav应该可以支持一下吗？

**Comment by Redns** [comment]
收到，已加入后续计划

**Comment by Redns** [comment]
`WebDAV` 备份功能已添加，可前往 [Release](https://github.com/Redns/picgo-plugin-autobackup/releases/tag/v1.5.2-beta) 下载安装

**Comment by Hello-XPH** [comment]
谢谢支持
